// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimNextPendingJob = `-- name: ClaimNextPendingJob :one
UPDATE jobs
SET status = 'Processing', started_at = now()
WHERE id = (
    SELECT id FROM jobs
    WHERE status = 'Pending'
    ORDER BY created_at
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, type, status, payload, created_at, started_at, completed_at
`

// Atomically claims the oldest pending job; SKIP LOCKED lets several workers poll concurrently.
func (q *Queries) ClaimNextPendingJob(ctx context.Context) (Job, error) {
	row := q.db.QueryRow(ctx, claimNextPendingJob)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Payload,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (id, type, payload)
VALUES ($1, $2, $3)
RETURNING id, type, status, payload, created_at, started_at, completed_at
`

type CreateJobParams struct {
	ID      uuid.UUID `json:"id"`
	Type    string    `json:"type"`
	Payload []byte    `json:"payload"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob, arg.ID, arg.Type, arg.Payload)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Payload,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createJobAttempt = `-- name: CreateJobAttempt :one
INSERT INTO job_attempts (id, job_id, attempt_number)
VALUES ($1, $2, $3)
RETURNING id, job_id, attempt_number, succeeded, error, started_at, finished_at
`

type CreateJobAttemptParams struct {
	ID            uuid.UUID `json:"id"`
	JobID         uuid.UUID `json:"job_id"`
	AttemptNumber int32     `json:"attempt_number"`
}

func (q *Queries) CreateJobAttempt(ctx context.Context, arg CreateJobAttemptParams) (JobAttempt, error) {
	row := q.db.QueryRow(ctx, createJobAttempt, arg.ID, arg.JobID, arg.AttemptNumber)
	var i JobAttempt
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.AttemptNumber,
		&i.Succeeded,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const createJobEvent = `-- name: CreateJobEvent :one
INSERT INTO job_events (id, job_id, type, data)
VALUES ($1, $2, $3, $4)
RETURNING id, job_id, type, data, created_at
`

type CreateJobEventParams struct {
	ID    uuid.UUID `json:"id"`
	JobID uuid.UUID `json:"job_id"`
	Type  string    `json:"type"`
	Data  []byte    `json:"data"`
}

func (q *Queries) CreateJobEvent(ctx context.Context, arg CreateJobEventParams) (JobEvent, error) {
	row := q.db.QueryRow(ctx, createJobEvent,
		arg.ID,
		arg.JobID,
		arg.Type,
		arg.Data,
	)
	var i JobEvent
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Type,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const createJobResult = `-- name: CreateJobResult :one
INSERT INTO job_results (id, job_id, data)
VALUES ($1, $2, $3)
RETURNING id, job_id, data, created_at
`

type CreateJobResultParams struct {
	ID    uuid.UUID `json:"id"`
	JobID uuid.UUID `json:"job_id"`
	Data  []byte    `json:"data"`
}

func (q *Queries) CreateJobResult(ctx context.Context, arg CreateJobResultParams) (JobResult, error) {
	row := q.db.QueryRow(ctx, createJobResult, arg.ID, arg.JobID, arg.Data)
	var i JobResult
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const finishJobAttempt = `-- name: FinishJobAttempt :one
UPDATE job_attempts
SET succeeded = $2, error = $3, finished_at = now()
WHERE id = $1
RETURNING id, job_id, attempt_number, succeeded, error, started_at, finished_at
`

type FinishJobAttemptParams struct {
	ID        uuid.UUID   `json:"id"`
	Succeeded bool        `json:"succeeded"`
	Error     pgtype.Text `json:"error"`
}

func (q *Queries) FinishJobAttempt(ctx context.Context, arg FinishJobAttemptParams) (JobAttempt, error) {
	row := q.db.QueryRow(ctx, finishJobAttempt, arg.ID, arg.Succeeded, arg.Error)
	var i JobAttempt
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.AttemptNumber,
		&i.Succeeded,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT id, type, status, payload, created_at, started_at, completed_at FROM jobs
WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id uuid.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Payload,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getJobResult = `-- name: GetJobResult :one
SELECT id, job_id, data, created_at FROM job_results
WHERE job_id = $1
`

func (q *Queries) GetJobResult(ctx context.Context, jobID uuid.UUID) (JobResult, error) {
	row := q.db.QueryRow(ctx, getJobResult, jobID)
	var i JobResult
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const listJobAttempts = `-- name: ListJobAttempts :many
SELECT id, job_id, attempt_number, succeeded, error, started_at, finished_at FROM job_attempts
WHERE job_id = $1
ORDER BY attempt_number
`

func (q *Queries) ListJobAttempts(ctx context.Context, jobID uuid.UUID) ([]JobAttempt, error) {
	rows, err := q.db.Query(ctx, listJobAttempts, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobAttempt{}
	for rows.Next() {
		var i JobAttempt
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.AttemptNumber,
			&i.Succeeded,
			&i.Error,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobEvents = `-- name: ListJobEvents :many
SELECT id, job_id, type, data, created_at FROM job_events
WHERE job_id = $1
ORDER BY created_at
`

func (q *Queries) ListJobEvents(ctx context.Context, jobID uuid.UUID) ([]JobEvent, error) {
	rows, err := q.db.Query(ctx, listJobEvents, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobEvent{}
	for rows.Next() {
		var i JobEvent
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Type,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByStatus = `-- name: ListJobsByStatus :many
SELECT id, type, status, payload, created_at, started_at, completed_at FROM jobs
WHERE status = $1
ORDER BY created_at
LIMIT $2
`

type ListJobsByStatusParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
}

func (q *Queries) ListJobsByStatus(ctx context.Context, arg ListJobsByStatusParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobsByStatus, arg.Status, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Status,
			&i.Payload,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobStatus = `-- name: UpdateJobStatus :one
UPDATE jobs
SET status = $1::text,
    completed_at = CASE WHEN $1::text IN ('Completed', 'Cancelled', 'Failed') THEN now() ELSE completed_at END
WHERE id = $2
RETURNING id, type, status, payload, created_at, started_at, completed_at
`

type UpdateJobStatusParams struct {
	Status string    `json:"status"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJobStatus, arg.Status, arg.ID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Payload,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}
