// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Job struct {
	ID          uuid.UUID  `json:"id"`
	Type        string     `json:"type"`
	Status      string     `json:"status"`
	Payload     []byte     `json:"payload"`
	CreatedAt   time.Time  `json:"created_at"`
	StartedAt   *time.Time `json:"started_at"`
	CompletedAt *time.Time `json:"completed_at"`
}

type JobAttempt struct {
	ID            uuid.UUID   `json:"id"`
	JobID         uuid.UUID   `json:"job_id"`
	AttemptNumber int32       `json:"attempt_number"`
	Succeeded     bool        `json:"succeeded"`
	Error         pgtype.Text `json:"error"`
	StartedAt     time.Time   `json:"started_at"`
	FinishedAt    *time.Time  `json:"finished_at"`
}

type JobEvent struct {
	ID        uuid.UUID `json:"id"`
	JobID     uuid.UUID `json:"job_id"`
	Type      string    `json:"type"`
	Data      []byte    `json:"data"`
	CreatedAt time.Time `json:"created_at"`
}

type JobResult struct {
	ID        uuid.UUID `json:"id"`
	JobID     uuid.UUID `json:"job_id"`
	Data      []byte    `json:"data"`
	CreatedAt time.Time `json:"created_at"`
}
