// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Atomically claims the oldest pending job; SKIP LOCKED lets several workers poll concurrently.
	ClaimNextPendingJob(ctx context.Context) (Job, error)
	CreateJob(ctx context.Context, arg CreateJobParams) (Job, error)
	CreateJobAttempt(ctx context.Context, arg CreateJobAttemptParams) (JobAttempt, error)
	CreateJobEvent(ctx context.Context, arg CreateJobEventParams) (JobEvent, error)
	CreateJobResult(ctx context.Context, arg CreateJobResultParams) (JobResult, error)
	FinishJobAttempt(ctx context.Context, arg FinishJobAttemptParams) (JobAttempt, error)
	GetJob(ctx context.Context, id uuid.UUID) (Job, error)
	GetJobResult(ctx context.Context, jobID uuid.UUID) (JobResult, error)
	ListJobAttempts(ctx context.Context, jobID uuid.UUID) ([]JobAttempt, error)
	ListJobEvents(ctx context.Context, jobID uuid.UUID) ([]JobEvent, error)
	ListJobs(ctx context.Context) ([]Job, error)
	ListJobsByStatus(ctx context.Context, arg ListJobsByStatusParams) ([]Job, error)
	UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) (Job, error)
}

var _ Querier = (*Queries)(nil)
